import tkinter as tk
rule=tk.Tk()
rule.minsize(1350,450)
rule.maxsize(1350,450)
r=tk.Label(rule,text='''HELLO AND WELCOME TO THIS FUN GAME CALLED FOOTBALL FUN WHERE YOU BATTLE IT OUT AGAINST THE COMPUTER AI IN ORDER TO GAIN ULTIMATE FOOTBALL GLORY!!!

DO YOU HAVE WHAT IT TAKES?

THE RULES OF THE GAME AR AS FOLLOWS:

1]YOU HAVE THE BALL AT THE START OF THE MATCH(CUZ THE AI DECIDED TO GO EASY ON YOU ;

2]CLICK ANY NUMBER ON THE BUTTONS INORDER TO PASS THE BALL OVER TO THAT PLAYER ;

3]IF THE COMPUTER AND YOU CHOOSE THE SAME NUMBER THEN THE BALL IS IN CONTROL WITH THE OTHER PLAYER ;

4]PASS THE BALL WITHOUT BEING BLOCKD BY THE COMPUTER 6 TIMES IN A ROW TO UNLOCK GOAL TIME ;

5]DURING GOAL TIME,YOU AMD THE COMPUTER WILL FACE OFF IN AN INTENSE 1V1 PENALTY SHOOT OUT ;

6]SELECT WHICH DIRECTION YOU WANT THE BALL TO KICK THE BALL AND ACCORDINGLY SELECT YOUR CHOICE;

7]AFTER SCORING, CLOSE THE GOAL TIME WINDOW AND PROCEED WITH PLAYING THE REST OF THE MATCH ;

8]YOU WIN THE GAME ONCE YOU SCORE 5 GOALS AND YOUR NAME WILL FOREVER BE REMEMBERED BY ALL THE FOOTBALL GREATS AS THE UNBEATABLE MASTER ;

9]GO START PLAYING!!!!!!!!''',fg='black',font='ArialBlack',bg='white')
r.pack()
rule.mainloop()
